apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel
resources:
  - ../../k8s
patches:
  - path: patch-config.yaml
    target:
      kind: ConfigMap
      name: sentinel-config
  - path: patch-ns.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: sentinel-actuator
  - path: patch-ns.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: sentinel-actuator
